[package]
name = "audiopipe"
version = "0.3.0"
edition = "2024"

[dependencies]
audiopipe-core = { path = "../audiopipe-core" }
clap = { version = "4.5.43", features = ["derive"] }
env_logger = "0.11.8"
tokio = { version = "1.47.1", features = ["full"] }
